# Snapshot report for `test/error-message.js`

The actual snapshot is saved in `error-message.js.snap`.

Generated by [AVA](https://avajs.dev).

## error-message - #1

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error()␊
        |       ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
    `

## error-message - #2

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw Error()␊
        |       ^^^^^^^ Pass a message to the `Error` constructor.␊
    `

## error-message - #3

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error('')␊
        |                 ^^ Error message should not be an empty string.␊
    `

## error-message - #4

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error(``)␊
        |                 ^^ Error message should not be an empty string.␊
    `

## error-message - #5

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const err = new Error();␊
        |             ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      2 | throw err;␊
    `

## error-message - #6

> Snapshot 1

    `␊
    Error 1/1:␊
      1 | let err = 1;␊
    > 2 | err = new Error();␊
        |       ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      3 | throw err;␊
    `

## error-message - #7

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | let err = new Error();␊
        |           ^^^^^^^^^^^ Pass a message to the `Error` constructor.␊
      2 | err = 1;␊
      3 | throw err;␊
    `

## error-message - #8

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const foo = new TypeError()␊
        |             ^^^^^^^^^^^^^^^ Pass a message to the `TypeError` constructor.␊
    `

## error-message - #9

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const foo = new SyntaxError()␊
        |             ^^^^^^^^^^^^^^^^^ Pass a message to the `SyntaxError` constructor.␊
    `

## error-message - #10

> Snapshot 1

    `␊
    Error 1/1:␊
      1 | const errorMessage = Object.freeze({errorMessage: 1}).errorMessage;␊
    > 2 | throw new Error(errorMessage)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## error-message - #11

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([])␊
        |                 ^^ Error message should be a string.␊
    `

## error-message - #12

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([foo])␊
        |                 ^^^^^ Error message should be a string.␊
    `

## error-message - #13

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error([0][0])␊
        |                 ^^^^^^ Error message should be a string.␊
    `

## error-message - #14

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({})␊
        |                 ^^ Error message should be a string.␊
    `

## error-message - #15

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({foo})␊
        |                 ^^^^^ Error message should be a string.␊
    `

## error-message - #16

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error({foo: 0}.foo)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## error-message - #17

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | throw new Error(lineNumber=2)␊
        |                 ^^^^^^^^^^^^ Error message should be a string.␊
    `

## error-message - #18

> Snapshot 1

    `␊
    Error 1/1:␊
    > 1 | const error = new RangeError;␊
        |               ^^^^^^^^^^^^^^ Pass a message to the `RangeError` constructor.␊
    `
